### ISSUE TITLE
How to disable eslint

### ISSUE THREAD

**Issue by kenshinman** [alan2207/nextjs-jwt-authentication#2]
Hi Thanks for this project really appreciate it. Please how do I disable eslint? It's causing me a whole lot of troubles. 👍  thanks

**Comment by alan2207** [comment]
Hi, I am really glad you like the project. If you don't want eslint you can remove it entirely from the project by deleting ".eslintrc.js" file, and deleting eslint devDependencies in "package.json". It should be fine...

**Comment by kenshinman** [comment]
Hey @alan2207 any plan to upgrade this to work with Next.Js 7?

**Comment by alan2207** [comment]
@kenshinman UPDATED!!! feel free to check it out....

**Comment by kenshinman** [comment]
Thanks @alan2207 . You rock!
