### ISSUE TITLE
Question: how to do a redirect if not logged in

### ISSUE THREAD

**Issue by pkyeck** [alan2207/nextjs-jwt-authentication#3]
First, thanks for this repo - big help!

I was looking at the `whoami.js` and wondering how exactly you'd do a redirect? Just as the `else` of the `if (token)` in the `Whoami.getInitialProps`? Or is it more complicated than that?

**Comment by alan2207** [comment]
Hi @pkyeck , I am glad you found it helpful.

Regarding your question:

If you can see, the `whoami` page isn’t redirecting unauthenticated users, it just says ‘You are not authenticated’. However, there is one thing where I handled redirection and that is when authenticated user is visiting `signin` and `signup` pages. If the user is authenticated and tries to enter one of the mentioned routes, the app redirects user to `/` route. 

For SSR, check out `signin` and `signup` routes in this file: https://github.com/alan2207/nextjs-jwt-authentication/blob/master/server.js  and for CSR you can check out `initialize` helper here: https://github.com/alan2207/nextjs-jwt-authentication/blob/master/utils/initialize.js  

I hope this answers your question :)

Cheers

**Comment by pkyeck** [comment]
ah, didn't think to look there - thanks!

**Comment by Germs31** [comment]
I still dont understand the redirect process so well. so what im understanding form this Q & A is that you can have the redirect happen from the Sever (server.js) or the Client from the Initialize.js file??
