### ISSUE TITLE
Inverted Reducers and Actions ?

### ISSUE THREAD

**Issue by Delkathes** [alan2207/nextjs-jwt-authentication#5]
May I ask. Didn't u invert Redux Actions and Reducers ?

I mean. Actions are supposed to be objects containing the payloads reducers "calculated" ?

Sorry, this probably doesn't deserve an "Issue report".

**Comment by alan2207** [comment]
@Delkathes 

No, I am pretty sure I didn't.  I am wondering what made you think that?

Actions are just plain objects describing change of state in the store. Reducers are pure functions that are determining how the state is being formed based on some actions.

Inside the `actions` folder in this app are action creators that are based on redux-thunk to handle async operations.

I hope this answers your question :)

**Comment by Delkathes** [comment]
You're obviously right. Completly forgot about redux-thunk ...
