### ISSUE TITLE
Remove Cookie

### ISSUE THREAD

**Issue by Viscmad** [alan2207/nextjs-jwt-authentication#6]
Same parameters are needed to be passed with cookie.remove() that where pass while cookie.set()

ie. 
```
cookie.set(key, value, {
			expires: 1,
			path: '/',
		});

cookie.remove(key, {
			expires: 1,
			path: '/', //==> Add path as well. Else cookie wont be deleted
		});
```

**Comment by alan2207** [comment]
Hi @Viscmad 

As per js-cookie docs:
https://github.com/js-cookie/js-cookie#basic-usage
https://github.com/js-cookie/js-cookie#path

The 'path' attribute defaults to '/', so it works in this case, even without setting it explicitly.

Thanks anyway.
